source 'https://github.com/CocoaPods/Specs.git'

target 'DMListener', :exclusive => true do
  pod "DMListener", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "DMListener", :path => "../"

  
end
